### ISSUE TITLE
Add plugin to the jenkins plugin repository

### ISSUE THREAD

**Issue by swestner** [achikin/testrail-jenkins-plugin#10]
It would be great if this could be added to the Jenkins plugin repository so it would be searchable and updatable through the Jenkins interface.

**Comment by achikin** [comment]
@swestner fill free to add it :)

**Comment by xirsoi** [comment]
Complete! https://github.com/jenkinsci/testrail-plugin

**Comment by achikin** [comment]
Great work @xirsoi !

**Comment by angelo-loria** [comment]
@xirsoi I am not seeing the plugin in the Jenkins plugin interface, can someone verify that?

Thanks!

**Comment by xirsoi** [comment]
@angelo-loria You are correct, I haven't managed to get it uploaded yet. I've gotten to the last step of the process, but I'm having some kind of auth error during the maven deploy.

I've been swamped at work the last couple weeks and haven't had a lot of time to dedicate to the problem.

**Comment by angelo-loria** [comment]
@xirsoi appreciate the response!

**Comment by jjensen554** [comment]
I'm at a point where this would perfect to have available before I go writing a temporary solution. Any status? Thank you.

**Comment by xirsoi** [comment]
I'll be making another attempt at this soon. For now you can add it manually by following the instructions in the readme.

**Comment by jjensen554** [comment]
I think I’m heading down that path – thanks. I’m contracting offsite for another company so have to deal with their IT to get it installed.
Thanks for the response.

**Comment by xirsoi** [comment]
Ok, I'm sorry I haven't got this figured out yet.

**Comment by jjensen554** [comment]
No problem. Appreciate all the work. If you have any ballpark idea of when that might be helpful.
Thanks,
Jack
