### ISSUE TITLE
Hosting the plugin in the Jenkins Update center

### ISSUE THREAD

**Issue by oleg-nenashev** [achikin/testrail-jenkins-plugin#13]
Hi @achikin , 

FYI in Jenkins org we have got a request for hosting one of the forks of this repo: https://issues.jenkins-ci.org/browse/HOSTING-237. It would be really useful to get the plugin publicly posted, but I'm not sure the proposed source repo is the right one. 

It would be great to sync-up with you and @xirsoi regarding the preferred fork/collaboration approach

Thanks in advance,
Oleg Nenashev
Jenkins Core Team

**Comment by xirsoi** [comment]
See Anton's comments [here](https://github.com/achikin/testrail-jenkins-plugin/issues/10) and [here](https://github.com/achikin/testrail-jenkins-plugin/issues/12).

**Comment by oleg-nenashev** [comment]
@xirsoi Thanks! it's enough for me
